### ISSUE TITLE
Can we give navigation goal?

### ISSUE THREAD

**Issue by iamrajee** [malintha/multi_uav_simulator#1]
After launching the simulation, how can we give a navigation goal?

**Comment by malintha** [comment]
If I remember correctly that's something under development in the dev branch. It depends on mav_trajectory_gen package [1] and can receive the sequence of goals. It also has receding horizon planning. But I have to update the readme with build instructions. 
[1] https://github.com/ethz-asl/mav_trajectory_generation

**Comment by malintha** [comment]
Check this line for starts. https://github.com/malintha/multi_uav_simulator/blob/dev/src/Quadrotor.cpp#L254

**Comment by iamrajee** [comment]
> Check this line for starts. https://github.com/malintha/multi_uav_simulator/blob/dev/src/Quadrotor.cpp#L254

Will do that, thank you.

**Comment by malintha** [comment]
Use this to publish the desired state goal to each robot as as a geometry_msgs::Point &pt. 
https://github.com/malintha/multi_uav_simulator/blob/dev/src/Quadrotor.cpp#L73

**Comment by Williamwenda** [comment]
Find here after launching a nearly empty Rviz. It would be great to provide some simple examples for those interested to play with the simulator. Thanks for sharing the code tho!

**Comment by malintha** [comment]
@Williamwenda I guess the config/simulation.rviz file has been missed out from the master branch. That populates the Rviz with robot models and other markers. I added that back in, so it should show the drones now. Thanks for pointing that out. 
And thanks for the great suggestion!

**Comment by Williamwenda** [comment]
@malintha Just tried it out. The simulation is pretty cool! Nice work, dude.

**Comment by malintha** [comment]
The support for publishing goals and RHP is now tested and needs to be merged to the master. Check: https://github.com/malintha/multi_uav_simulator/pull/5.

**Comment by iamrajee** [comment]
> The support for publishing goals and RHP is now tested and needs to be merged to the master. Check: #5.

Thank you :)

**Comment by malintha** [comment]
@iamrajee There are some conflicts needs to be resolved before merging. But feel free to give it a try from the dev branch. I'd be happy know hear any inputs (or if anything's broken before merging). :)
